# Generated by Django 5.1.2 on 2024-11-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
